import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Shared/Footer/Footer";
import Navbar from "./components/Shared/NavBar/Navbar";
import { CurrencyProvider } from "./assets/Functions/CurrencyContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CurrencyProvider>
          <Navbar />
          {children}
          <Footer />
        </CurrencyProvider>
      </body>
    </html>
  );
}
